### ISSUE TITLE
SQLi is not working in without risk parameter

### ISSUE THREAD

**Issue by punitdarji** [shenril/Sitadel#41]
## Environment

- OS: Windows 10
- Python version 3.7
- Sitadel version

I have tested on my virtual environment with list of vulnerabilities such as XSS and SQLi. XSS is detect properly but SQLi is not detect. The vulnerability is simple to add quotation marks after ID such as localhost/xyz/catagory.php?id=23' 

Also, I would like to add vulnerabilities and CVE in the tool.

**Comment by shenril** [comment]
Hello, 

I decided to put a higher risk on the SQLi because there is a potential impact on the database and the data. You would like to add some SQLi with lower risk ?

You re welcome to add any CVE to the tool ! 
You can add a file in lib/modules/attacks/vulns with the vulnerabilities you want to add. 
It will be loaded automatically when you call the tool.

**Comment by punitdarji** [comment]
Thanks Shenril/Sitadel I will look into it and get back to you.

**Comment by punitdarji** [comment]
Is it possible to change all risk in only in one module? Also, I would like to add PDF report in the tool. could you possibly provide documentation?

**Comment by shenril** [comment]
At the moment you cannot choose the risk per module because it s too hard to specify on the CLI parameters. But if you have an idea about it I could try to implement it. 

Regarding the PDF, what would like to see in it ? Just the text with the vulnerabilities ?

**Comment by punitdarji** [comment]
I am trying to give just a link and users don't have to specify any risk parameter. Regarding PDF, all cmd output or log should export in the pdf file. Is it possible to contact you?
